services:
  postgres:
    image: postgres:13
    container_name: mimic4-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mimic4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../data/mimic-iv-clinical-database-demo-2.2:/mimic-iv
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: mimic4-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:
