# Datenbankkonfiguration für die Gold-Ebene

database:
  host: "localhost"
  port: 5432
  database: "postgres"
  user: "postgres"
  password: "postgres"
  schema_input: "silver_schema"
  schema_output: "gold_schema"
# Datenbankkonfiguration für die Gold-Ebene

database:
  host: localhost
  port: 5432
  database: mimic4
  user: postgres
  password: postgres
  schema_input: silver_schema
  schema_output: gold_schema
