# Alternative Konfiguration für SOFA-Score mit anderer Imputationsmethode

database:
  host: localhost
  port: 5432
  database: mimic4
  user: postgres
  password: postgres
  schema_input: silver_schema
  schema_output: gold_schema

input_table: standardized_parameters

# Pivot-Konfiguration
pivot:
  index_cols: ['subject_id', 'hadm_id', 'stay_id', 'charttime']
  value_col: 'value'
  pivot_col: 'concept_name'

# Aggregations-Konfiguration
aggregation:
  time_window: '24H'
  method: 'median'  # Median statt Mittelwert
  offset: '1H'

# Imputations-Konfiguration
imputation:
  method: 'median'  # Median-Imputation statt Forward-Fill
  group_by: ['subject_id', 'hadm_id', 'stay_id']
  fill_remaining: true
  fill_method: 'median'

# Abgeleitete Parameter
derived_parameters:
  - name: 'PaO2_FiO2_ratio'
    formula: '$["Oxygen [Partial pressure] in Arterial blood"] / 0.21'  # Annahme: FiO2 = 21% wenn nicht vorhanden
    required_columns: ["Oxygen [Partial pressure] in Arterial blood"]
  
  - name: 'MAP'
    formula: '($["Systolic blood pressure"] + 2 * $["Diastolic blood pressure"]) / 3'  # (Systolic blood pressure + 2 * Diastolic blood pressure) / 3
    required_columns: ["Systolic blood pressure", "Diastolic blood pressure"]

# SOFA-Score Komponenten
clinical_scores:
  - name: 'SOFA_score'
    components:
      - name: 'respiratory'
        parameter: 'PaO2_FiO2_ratio'
        thresholds: [400, 300, 200, 100]
        scores: [0, 1, 2, 3, 4]
      
      - name: 'coagulation'
        parameter: "Platelets"  # 3007461
        thresholds: [150, 100, 50, 20]
        scores: [0, 1, 2, 3, 4]
      
      - name: 'liver'
        parameter: "Bilirubin.total"  # 3024128
        thresholds: [1.2, 2.0, 6.0, 12.0]
        scores: [0, 1, 2, 3, 4]
      
      - name: 'cardiovascular'
        parameter: 'MAP'  # Verwende den berechneten MAP
        thresholds: [70, 65]
        scores: [0, 1, 2, 3, 4]  # Vereinfacht, eigentlich abhängig von Vasopressoren
      
      - name: 'cns'
        parameter: "Glasgow Coma Scale total"  # 3007194
        thresholds: [14, 12, 9, 5]
        scores: [0, 1, 2, 3, 4]
      
      - name: 'renal'
        parameter: "Creatinine"  # 3016723
        thresholds: [1.2, 2.0, 3.5, 5.0]
        scores: [0, 1, 2, 3, 4]

# Speichern der Teilscores aktivieren
save_score_components: true

output_table: sofa_alternative
