# SOFA-Score Konfiguration mit 24h Forward-Fill-Imputation
pipeline:
  input_table: standardized_parameters
  output_table: gold_sofa_24h_forwardfill
  pivot_data: true
  aggregate_data: true
  impute_missing_values: true
  calculate_derived_parameters: true
  calculate_clinical_scores: true

pivot:
  index_cols: ['subject_id', 'charttime']
  value_col: 'value'
  pivot_col: 'concept_name'

aggregation:
  time_window: '1H'
  method: 'mean'

imputation:
  method: 'locf'  # Last Observation Carried Forward
  group_by: ['subject_id']

derived_parameters:
  - name: 'PaO2_FiO2_ratio'
    formula: '$["Oxygen [Partial pressure] in Arterial blood"] / 0.21'  # Annahme: FiO2 = 21% wenn nicht vorhanden
    required_columns: ["Oxygen [Partial pressure] in Arterial blood"]
  
  - name: 'MAP'
    formula: '($["Systolic blood pressure"] + 2 * $["Diastolic blood pressure"]) / 3'
    required_columns: ["Systolic blood pressure", "Diastolic blood pressure"]

clinical_scores:
  - name: 'SOFA_score'
    components:
      - name: 'respiratory'
        parameter: 'PaO2_FiO2_ratio'
        thresholds: [400, 300, 200, 100]
        scores: [0, 1, 2, 3, 4]
        direction: 'descending'  # Niedrigere Werte sind schlechter
      
      - name: 'coagulation'
        parameter: 'Platelets'
        thresholds: [150, 100, 50, 20]
        scores: [0, 1, 2, 3, 4]
        direction: 'descending'  # Niedrigere Werte sind schlechter
      
      - name: 'liver'
        parameter: 'Bilirubin.total'
        thresholds: [1.2, 2.0, 6.0, 12.0]
        scores: [0, 1, 2, 3, 4]
        direction: 'ascending'  # Höhere Werte sind schlechter
      
      - name: 'cardiovascular'
        parameter: 'MAP'
        thresholds: [70, 65]
        scores: [0, 1, 2, 3, 4]  # Vereinfacht, eigentlich abhängig von Vasopressoren
        direction: 'descending'  # Niedrigere Werte sind schlechter
      
      - name: 'cns'
        parameter: 'Glasgow Coma Scale total'
        thresholds: [14, 12, 9, 5]
        scores: [0, 1, 2, 3, 4]
        direction: 'descending'  # Niedrigere Werte sind schlechter
      
      - name: 'renal'
        parameter: 'Creatinine'
        thresholds: [1.2, 2.0, 3.5, 5.0]
        scores: [0, 1, 2, 3, 4]
        direction: 'ascending'  # Höhere Werte sind schlechter
